Initial commit for SNMP gui form
freenas/gui pull request #108
Opened 2016-10-05 21:15 UTC by erinix

Ticket: #17866

2016-10-05 23:34 UTC, pchaussalet requested changes

2016-10-05 23:34 UTC, pchaussalet commented on ui/inspectors/service.reel/snmp-service.reel/snmp-service.js
> +          this.v3privacyprotocol = ServiceSnmpV3privacyprotocol.members
Property names should be camelCased.

2016-10-05 23:49 UTC, erinix commented
ready for review again

2016-10-06 00:08 UTC, pchaussalet approved these changes

2016-10-06 00:08 UTC, merged