Add active_media_type and capabilities to network interface ui
freenas/gui pull request #127
Opened 2016-10-12 01:01 UTC by erinix

Ticket: #18069

Need some prettification on the capabilities section since it goes off screen.

2016-10-12 01:34 UTC, jordanhubbard reviewed
One suggestion would be that rather than trying to even vaguely use an option string like RXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,VLAN_HWTSO,RXCSUM_IPV6 (there can be even more, maybe even over a dozen, with more complex interface types) we instead break the <options> on comma boundaries and turn it into a single scrolling list, maybe 4 entries high by default, so that it can contain double-digit entry counts without blowing up the real-estate requirements.

2016-10-12 15:01 UTC, joshuarule commented
@jordanhubbard were you thinking something like this? https://cl.ly/hkRE

2016-10-12 15:32 UTC, jordanhubbard commented
Yep, exactly like that!

2016-10-13 01:49 UTC, erinix commented
Pierre, could you review?

2016-10-13 02:28 UTC, pchaussalet requested changes

2016-10-13 02:28 UTC, pchaussalet commented on ui/sections/network/inspectors/network-interface.reel/interface.reel/interface.js
> +            self.active_media_type = this.object.status.active_media_type.concat(" ", this.object.status.active_media_subtype);
`this.object` is not guaranteed to be set when `templateDidLoad` is called. Moreover, `templateDidLoad` is only called once when the component is first loaded, so it won't reflect object changes.
This code should be moved to `enterDocument`.

2016-10-13 02:28 UTC, pchaussalet commented on ui/sections/network/inspectors/network-interface.reel/interface.reel/interface.js
> +            self.active_media_type = this.object.status.active_media_type.concat(" ", this.object.status.active_media_subtype);
You should use `+` instead of `concat` (`concat` has bad performances)

2016-10-13 02:28 UTC, pchaussalet commented on ui/sections/network/inspectors/network-interface.reel/interface.reel/interface.js
> +            self.active_media_type = this.object.status.active_media_type.concat(" ", this.object.status.active_media_subtype);
You shouldn't use `self` here, there is no context switching.

2016-10-13 19:31 UTC, pchaussalet approved these changes
LGTM

2016-10-13 19:31 UTC, merged