Boot pool table refactor
freenas/gui pull request #180
Opened 2016-10-31 19:37 UTC by joshuarule

2016-10-31 19:46 UTC, joshuarule commented
requires merge of https://github.com/freenas/blue-shark/pull/14

2016-11-01 19:03 UTC, pchaussalet requested changes

2016-11-01 19:03 UTC, pchaussalet commented on ui/inspectors/system-section.reel/boot-pool.reel/boot-environment-row.reel/boot-environment-row.js
> +    constructor: {
You should remove this method, it doesn't do anything, it is just some noise added by `minit`.

2016-11-01 19:03 UTC, pchaussalet commented on ui/inspectors/system-section.reel/boot-pool.reel/boot-pool-action.reel/_boot-pool-action.css
> +    /* display: flex; */
You should remove those lines completely.

2016-11-01 19:03 UTC, pchaussalet commented on ui/inspectors/system-section.reel/boot-pool.reel/boot-pool-action.reel/_boot-pool-action.css
> +    /* flex: 1; */
Same here.

2016-11-01 19:03 UTC, pchaussalet commented on ui/inspectors/system-section.reel/boot-pool.reel/boot-pool.js
> +            if(event.detail && event.detail.get('eventName') == 'textValueChanged') {
@thibaultzanini Any opinion on this ?

2016-11-01 22:58 UTC, pchaussalet approved these changes

2016-11-01 22:58 UTC, pchaussalet commented
LGTM

2016-11-02 00:52 UTC, joshuarule commented
this was merged manually

2016-11-02 00:52 UTC, closed without merging