static routes & host entries
freenas/gui pull request #190
Opened 2016-11-02 16:51 UTC by hans-vm

Added static routes & host entries section to the Network/Settings.

2016-11-02 20:12 UTC, pchaussalet requested changes

2016-11-02 20:12 UTC, pchaussalet commented on core/converter/ip-addresses-converter.js
> + exports.IpAddressesConverter = Converter.specialize({
Shouldn't this be called in a more generic way ? It has nothing specific to ip addresses, something like `StringToArray`, maybe ?

2016-11-02 20:12 UTC, pchaussalet commented on core/dao/network-host-dao.js
> +            this._model = Model.NetworkHost;
`Model` is available at `this.constructor.Model`, no need to require it here.

2016-11-02 20:12 UTC, pchaussalet commented on core/dao/network-route-dao.js
> +            this._model = Model.NetworkRoute;
`Model` is available at `this.constructor.Model`, no need to require it here.

2016-11-02 20:12 UTC, pchaussalet commented on ui/abstract/abstract-multiple-edit-controller.js
> +            this.values.forEach(function(value) {
Please avoid using `forEach`, as it has terrible performances.

2016-11-02 20:12 UTC, pchaussalet commented on ui/abstract/abstract-multiple-edit-controller.js
> +            this._objects.forEach(function(object) {
Same here.

2016-11-02 20:12 UTC, pchaussalet commented on ui/abstract/abstract-multiple-edit-controller.js
> +            return this._dataService.getNewInstanceForType(type)
Isn't there a way to avoid using `dataService` directly from the component ? It shouldn't be component's concern to directly save data.

2016-11-02 20:12 UTC, pchaussalet commented on ui/sections/network/controls/table-routes.reel/table-routes.js
> +    mapObjectToRawData: {
Raw data notion must not be known to the component. This kind of mapping needs to be done only by the ORM (in our case, montage-data).

2016-11-02 20:32 UTC, hans-vm commented on core/converter/ip-addresses-converter.js
> + exports.IpAddressesConverter = Converter.specialize({
I thought we could add validator for individual ip addresses but removed it before commit because it seems not to be collaborating with Component. (I guess Inspectors doing it). Maybe I'll just change it to StringToArrayConverter and come back to it later.

2016-11-03 18:54 UTC, pchaussalet approved these changes

2016-11-03 19:03 UTC, merged