Fixed: disable editable fileds when it's read_only
freenas/gui pull request #232
Opened 2016-11-12 22:58 UTC by mactanxin

ticket: #18775

2016-11-12 23:38 UTC, pchaussalet requested changes

2016-11-12 23:38 UTC, pchaussalet commented on ui/inspectors/user.reel/user.html
> +                "canDelete": {"<-": "!@owner.object.origin.read_only"},
the existing conditions are still valid, `origin.read_only` is just another condition

2016-11-12 23:38 UTC, pchaussalet commented on ui/inspectors/user.reel/user.html
> +                "switchValue": {"<-": "!!@owner.object.origin.read_only ? 'system' : 'luser'"}
Same here

2016-11-13 00:57 UTC, mactanxin commented
updated

2016-11-13 05:55 UTC, pchaussalet approved these changes

2016-11-13 05:57 UTC, merged