Ticket #19186
freenas/gui pull request #310
Opened 2016-12-05 19:04 UTC by hans-vm

Added "quick creation" mode for snapshot.

2016-12-06 20:36 UTC, thibaultzanini approved these changes
LGTM

2016-12-07 22:58 UTC, thibaultzanini requested changes
There is no more default value if I switch between the property expire between `at` and `after`

2016-12-08 11:54 UTC, hans-vm commented
@thibaultzanini Yeah, that's a recognized bug and I believe the fix should be made in the blue-shark ui, so I was going to talk to @joshuarule about it. 
I was kinda waiting for it to be merged, so that he can also reproduce it on his side. 
And if you look more closely into it, there's one more issue there, where the repetition duration control doesn't correctly reset when you open create snapshot UI multiple times, it simply because the duration control doesn't accept `0` as a valid input.
I believe I could collaborate with @joshuarule to make the duration control somewhat more flexible and of course, to appreciate `0`. 😄

2016-12-08 20:26 UTC, thibaultzanini approved these changes

2016-12-08 20:26 UTC, merged