Ticket #19249
freenas/gui pull request #312
Opened 2016-12-06 17:10 UTC by hans-vm

Added easy replicate option to volume/dataset

2016-12-06 20:44 UTC, thibaultzanini requested changes

2016-12-06 20:44 UTC, thibaultzanini commented on ui/sections/storage/inspectors/volume-dataset.reel/volume-dataset.js
> +                this.application.dataService.getNewInstanceForType(Model.ReplicationOptions)
We try to go away from that design, the storage-section-service should have a method that return a new instance of ReplicationOptions. :)

2016-12-07 22:59 UTC, thibaultzanini approved these changes
LGTM

2016-12-07 23:30 UTC, thibaultzanini commented
@pchaussalet Can you double check this one please.

2016-12-07 23:34 UTC, pchaussalet commented
Looks good to me

2016-12-08 18:55 UTC, merged