Task panel (WiP)
freenas/gui pull request #313
Opened 2016-12-06 21:32 UTC by mactanxin

overview page, non-scrollable(yet)

2016-12-07 23:37 UTC, thibaultzanini requested changes

2016-12-07 23:37 UTC, thibaultzanini commented on core/repository/task-repository.js
> +            return this._taskDao.find({}, true, 25);
why the first argument is an empty object here? @pchaussalet

2016-12-07 23:37 UTC, thibaultzanini commented on core/repository/task-repository.js
> +            return this._taskDao.find(filter, true, Object.keys(filter).length > 0 ? 0 : 25);
I hope find will always return an array.

2016-12-07 23:37 UTC, thibaultzanini commented on core/service/task-service.js
> +var task_repository_1 = require("core/repository/task-repository");
Why the number `1` at the end? not camelCase

2016-12-07 23:37 UTC, thibaultzanini commented on core/service/task-service.ts
> +export class TaskService {
Ah I'm pretty happy to see some typescript here. :)

2016-12-07 23:37 UTC, thibaultzanini commented on core/service/task-service.ts
> +    public loadEntries(): Promise< Array<Object> > {
space between `<` and `Array`

2016-12-07 23:37 UTC, thibaultzanini commented on core/service/task-service.ts
> +    public findTasks(filter: Object): Promise< Array<Object>> {
same here

2016-12-07 23:37 UTC, thibaultzanini commented on ui/sections/task/controls/table-task.reel/table-task-header.reel/table-task-header.css
> +}
missing end line

2016-12-07 23:37 UTC, thibaultzanini commented on ui/sections/task/controls/table-task.reel/table-task-header.reel/table-task-header.js
> +    constructor: {
you can remove this empty constructor :)

2016-12-07 23:37 UTC, thibaultzanini commented on ui/sections/task/controls/table-task.reel/table-task-row.reel/table-task-row.js
> +    constructor: {
same here

2016-12-07 23:37 UTC, thibaultzanini commented on ui/sections/task/controls/table-task.reel/table-task.css
> +}
same here

2016-12-07 23:37 UTC, thibaultzanini commented on ui/sections/task/inspectors/tasks.reel/tasks.html
> +<<<<<<< HEAD
I guess there were some conflicts here.

2016-12-07 23:37 UTC, thibaultzanini commented on ui/sections/task/inspectors/tasks.reel/tasks.js
> +            console.log(filter);
you should remove this console.log

2016-12-07 23:43 UTC, pchaussalet commented on core/repository/task-repository.js
> +            return this._taskDao.find({}, true, 25);
Because it is an empty filter

2016-12-07 23:44 UTC, pchaussalet commented on core/repository/task-repository.js
> +            return this._taskDao.find(filter, true, Object.keys(filter).length > 0 ? 0 : 25);
Why ?

2016-12-07 23:44 UTC, pchaussalet commented on core/service/task-service.js
> +var task_repository_1 = require("core/repository/task-repository");
TS FTW ! ;)

2016-12-08 19:46 UTC, thibaultzanini commented on core/repository/task-repository.js
> +            return this._taskDao.find({}, true, 25);
why not just send null? instead of making a empty object.

2016-12-08 19:46 UTC, thibaultzanini commented on core/repository/task-repository.js
> +            return this._taskDao.find(filter, true, Object.keys(filter).length > 0 ? 0 : 25);
my bad I read too quickly

2016-12-08 19:57 UTC, thibaultzanini requested changes
I can't use it, issue with the date range http://d.pr/i/1pVu

2016-12-08 20:29 UTC, merged