Add "SASL wrapping" field to AD directory params.
freenas/gui pull request #314
Opened 2016-12-06 21:47 UTC by jceel

Ticket: #19252

2016-12-07 23:42 UTC, thibaultzanini requested changes
Just a little change required otherwise looks good to me :)

2016-12-07 23:42 UTC, thibaultzanini commented on ui/inspectors/directory-services.reel/winbind-service.reel/winbind-service.html
> +                "options": [
looks like you could require the enum `LdapDirectoryParamsSaslWrapping` within the controller and bind the `options` property of the select component to the `members` property of the enum.

2016-12-08 17:52 UTC, jceel commented on ui/inspectors/directory-services.reel/winbind-service.reel/winbind-service.html
> +                "options": [
Please show me some example.

2016-12-13 17:47 UTC, pchaussalet commented on ui/inspectors/directory-services.reel/winbind-service.reel/winbind-service.html
> +                "options": [
you can refer to this as an example: https://github.com/freenas/gui/blob/master/ui/sections/system/inspectors/alert.reel/table-predicates.reel/table-row-predicate.reel/table-row-predicate.js#L29

2016-12-22 23:29 UTC, closed without merging