Fix: certificate display US country only
freenas/gui pull request #330
Opened 2016-12-12 21:28 UTC by mactanxin

ticket: #19502

2016-12-13 17:50 UTC, pchaussalet requested changes

2016-12-13 17:50 UTC, pchaussalet commented on ui/sections/system/inspectors/crypto-certificate.reel/crypto-certificate-creation.reel/crypto-certificate-creation.js
> +            if (this.object._isNew == true) {
this.object._isNew is a boolean, no need to compare it to `true`

2016-12-13 17:51 UTC, pchaussalet commented
there is a conflict on `ui/inspectors/system-section.reel/mail.reel/mail.html`

2016-12-15 01:17 UTC, mactanxin commented
updated. conflict fixed

2016-12-15 20:14 UTC, pchaussalet approved these changes
LGTM

2016-12-15 20:14 UTC, merged