Fix alert filter doesn't work properly
freenas/gui pull request #392
Opened 2017-01-11 22:45 UTC by mactanxin

ticket: #19828

2017-01-12 20:18 UTC, pchaussalet approved these changes
LGTM

2017-01-12 20:24 UTC, pchaussalet requested changes

2017-01-12 20:24 UTC, pchaussalet commented on ui/sections/system/inspectors/alert.reel/table-predicates.reel/table-predicates.js
> +                switch (this.rows[0].property) {
You could have used something like
```
property = _.head(_.reject(["class", "severity"], function(x) { return x === self.rows[0].property; }));
```

2017-01-13 19:33 UTC, mactanxin commented
updated

2017-01-13 19:36 UTC, pchaussalet approved these changes
LGTM

2017-01-13 19:36 UTC, merged