fixed smb share regressions
freenas/gui pull request #402
Opened 2017-01-16 16:56 UTC by hans-vm

2017-01-17 00:27 UTC, pchaussalet requested changes

2017-01-17 00:27 UTC, pchaussalet commented on src/service/share-service.js
> +            // delete shareObject.permissions.user;
Can you remove it instead of commenting out ?

2017-01-17 14:07 UTC, hans-vm commented on src/service/share-service.js
> +            // delete shareObject.permissions.user;
I thought someone added it for purpose and it might be required for other type of shares other than smb shares.
Removed as per your request.

2017-01-18 00:59 UTC, pchaussalet approved these changes
LGTM

2017-01-18 01:00 UTC, merged