Fix 20912
freenas/gui pull request #476
Opened 2017-02-08 20:54 UTC by thibaultzanini

2017-02-09 20:55 UTC, pchaussalet requested changes

2017-02-09 20:55 UTC, pchaussalet commented on ui/sections/containers/controls/docker-image-search.reel/docker-image-search.js
> +        set (promise) {
A colon is missing...

2017-02-13 20:34 UTC, thibaultzanini commented
PR updated

2017-02-14 03:03 UTC, pchaussalet approved these changes

2017-02-14 03:03 UTC, merged