Add Tunable section
freenas/gui pull request #58
Opened 2016-09-14 20:31 UTC by mactanxin

for ticket https://bugs.freenas.org/issues/15645

2016-09-14 22:01 UTC, pchaussalet commented on ui/inspectors/tunable.reel/tunable.html
> +                "confirmationMessage": {"<-": "'Are you sure you want to delete ' + @owner.object.id + '?'"}
I'm not sure the `object.id` property is the most meaningful to the user to make sure what he is about to delete. I think `object.var` would be a better candidate.

2016-09-14 22:04 UTC, pchaussalet commented on ui/inspectors/tunable.reel/tunable.js
> +                tunableType = TunableType;
Useless, you should just use `TunableType`

2016-09-14 22:10 UTC, pchaussalet commented on ui/inspectors/tunable.reel/tunable.js
> +                    this.typeOPTIONS.push({label: tunableType.members[i], value: tunableType[tunableType.members[i]]});
The select-option-converter is made to do that conversion for you.
Just put the content of `TunableType.members` in `this.typeOptions` and instantiate the select-option-converter like this in the serialization: 
```
"tunableTypeOptionConverter": {
    "prototype": "core/converter/select-option-converter",
    "properties": {
        "labelPropertyName": "this",
        "valuePropertyName": "this"
},
```

2016-09-14 22:11 UTC, pchaussalet commented on ui/inspectors/tunable.reel/tunable.js
> +    typeOPTIONS: {
Please use camelCasing for properties names.

2016-09-14 22:12 UTC, pchaussalet requested changes

2016-09-14 23:08 UTC, pchaussalet commented on ui/inspectors/tunable.reel/tunable.js
> +                EnumTunableType = TunableType;
EnumTunableType is useless.

2016-09-14 23:11 UTC, pchaussalet commented on ui/inspectors/tunable.reel/tunable.js
> +                this.typeOptions = [];
You should just assign `TunableType.members` to `this.typeOptions`, no need to iterate by yourself.
Also you should do this in `templateDidLoad` (everything that is run only once and doesn't need to read a bound variable should go in `templateDidLoad`).

2016-09-15 16:31 UTC, pchaussalet commented on ui/inspectors/tunable.reel/tunable.js
> +            var self = this;
`self` is not used in this method.

2016-09-15 16:32 UTC, pchaussalet commented on ui/inspectors/tunable.reel/tunable.js
> +                this.typeOptions = TunableType.members;
This should be moved in the `templateDidLoad` method to ensure there is no flickering due to the options loading.

2016-09-15 16:33 UTC, pchaussalet commented on ui/inspectors/tunable.reel/tunable.js
> +                if (!this.object.type) {
It can be simplified in a single `if` condition.

2016-09-15 16:33 UTC, pchaussalet requested changes

2016-09-15 18:11 UTC, mactanxin commented on ui/inspectors/tunable.reel/tunable.js
> +            var self = this;
`self` is used

2016-09-16 16:24 UTC, pchaussalet approved these changes

2016-09-16 16:25 UTC, merged